[package]
name = "cargo-patch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version="4.5.2", features=["derive"] }
# serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.13"
